version: "3.3"

services:
  node:
    image: node
    container_name: node
    restart: always
    volumes:
      - ./src:/home/app
    working_dir: /home/app
    ports:
    #  - 3000:3000 #react dev
      - 80:5000 #server
    #command: npm run start-dev
    command: npm run start
    env_file: .env
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./db_data:/data/db